serenity.project.name=BidMart Catalog Service Functional Tests
serenity.outputDirectory=build/site/serenity
serenity.test.root=build/site/serenity
serenity.requirement.types=feature,story
report.customfields.Application=BidMart Catalog Service
report.customfields.Module=Catalog and Listings
report.customfields.Test Type=Functional and Integration
