spring:
  application:
    name: catalog
  datasource:
    url: ${SPRING_DATASOURCE_URL:${SUPABASE_DB_URL:}}
    username: ${SPRING_DATASOURCE_USERNAME:${SUPABASE_DB_USERNAME:sa}}
    password: ${SPRING_DATASOURCE_PASSWORD:${SUPABASE_DB_PASSWORD:}}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
service:
  auction:
    url: ${AUCTION_SERVICE_INTERNAL_URL:${AUCTION_INTERNAL_SERVICE_URL:http://localhost:8082/api/auctions/internal/}}
  auth:
    url: ${AUTH_INTERNAL_SERVICE_URL:http://localhost:8081/api/internal/users/}
    internal-token: ${AUTH_INTERNAL_SERVICE_TOKEN:bidmart-internal-dev-token}

staging:
  links:
    frontend-url: ${FRONTEND_STAGING_URL:not-set}
    backend-url: ${BACKEND_STAGING_URL:not-set}
    database-url: ${DATABASE_STAGING_URL:not-set}
