spring:
  application:
    name: catalog
  datasource:
    url: ${SUPABASE_DB_URL:}
    username: ${SUPABASE_DB_USERNAME:sa}
    password: ${SUPABASE_DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
service:
  auction:
    url: ${AUCTION_INTERNAL_SERVICE_URL:http://localhost:8082/api/auctions/internal/}
  auth:
    url: ${AUTH_INTERNAL_SERVICE_URL:http://35.168.202.46:8081/api/internal/users/}

staging:
  links:
    frontend-url: ${FRONTEND_STAGING_URL:not-set}
    backend-url: ${BACKEND_STAGING_URL:not-set}
    database-url: ${DATABASE_STAGING_URL:not-set}
